export type ChecklistItem = {
    id: number;
    category: string;
    task: string;
    completed: boolean;
};

export const checklistData: ChecklistItem[] = [
    // Website Development
    {
        id: 1,
        category: 'Website Development',
        task: 'Finalize & Gather client needs',
        completed: false,
    },
    {
        id: 2,
        category: 'Website Development',
        task: 'Secure website domain & hosting',
        completed: false,
    },
    {
        id: 3,
        category: 'Website Development',
        task: 'During onboarding meeting, clarify the services they want on the website (if SEO team did not clarify)',
        completed: false,
    },
    {
        id: 4,
        category: 'Website Development',
        task: 'During onboarding meeting, ask for USP (if PPC team did not clarify)',
        completed: false,
    },
    {
        id: 5,
        category: 'Website Development',
        task: 'Design base pages',
        completed: false,
    },
    {
        id: 6,
        category: 'Website Development',
        task: 'Design approval from client',
        completed: false,
    },
    {
        id: 7,
        category: 'Website Development',
        task: 'Prepare staging site for development',
        completed: false,
    },

    // Install necessary plugins and themes
    {
        id: 8,
        category: 'Install necessary plugins and themes',
        task: 'Install latest WordPress version',
        completed: false,
    },
    {
        id: 9,
        category: 'Install necessary plugins and themes',
        task: 'Install TCJ Blank Hello Elementor Theme and Child theme',
        completed: false,
    },
    {
        id: 10,
        category: 'Install necessary plugins and themes',
        task: 'Install Elementor plugin and Elementor pro plugin',
        completed: false,
    },
    {
        id: 11,
        category: 'Install necessary plugins and themes',
        task: 'Activate Elementor pro plugin',
        completed: false,
    },
    {
        id: 12,
        category: 'Install necessary plugins and themes',
        task: 'Develop web pages based on design',
        completed: false,
    },
    {
        id: 13,
        category: 'Install necessary plugins and themes',
        task: 'Disable auto updates for Elementor & WPRocket',
        completed: false,
    },
    {
        id: 14,
        category: 'Install necessary plugins and themes',
        task: 'Coordinate with Content writers to finilaze web page contents',
        completed: false,
    },
    {
        id: 15,
        category: 'Install necessary plugins and themes',
        task: 'Final checking with client for site launch',
        completed: false,
    },

    // Launch new website
    {
        id: 16,
        category: 'Launch new website',
        task: 'Install SG Security plugin (Install WP Activity Log if not hosted in Siteground)',
        completed: false,
    },
    {
        id: 17,
        category: 'Launch new website',
        task: 'Install WP Rocket plugin',
        completed: false,
    },
    {
        id: 18,
        category: 'Launch new website',
        task: 'Install Imagify plugin',
        completed: false,
    },
    {
        id: 19,
        category: 'Launch new website',
        task: 'Configure WP Rocket plugin through importing pre-made settings',
        completed: false,
    },
    {
        id: 20,
        category: 'Launch new website',
        task: 'Install RankMath SEO plugin',
        completed: false,
    },
    {
        id: 21,
        category: 'Launch new website',
        task: 'Install Call now Button plugin',
        completed: false,
    },
    {
        id: 22,
        category: 'Launch new website',
        task: 'Add new GSC as Domain property, install the TXT code via Hosting, & verify it.',
        completed: false,
    },
    {
        id: 23,
        category: 'Launch new website',
        task: 'Add new GTM account & install GTM codes via Elementor Custom Code',
        completed: false,
    },
    {
        id: 24,
        category: 'Launch new website',
        task: 'Add new Google Analytics account & install the code.',
        completed: false,
    },
    {
        id: 25,
        category: 'Launch new website',
        task: 'Install UTM code via Elementor Custom code (for GBP submissions tracking)',
        completed: false,
    },
    {
        id: 26,
        category: 'Launch new website',
        task: 'Install Google Recaptcha',
        completed: false,
    },
    {
        id: 27,
        category: 'Launch new website',
        task: 'Improve page speed via WP Rocket and Imagify',
        completed: false,
    },
    {
        id: 28,
        category: 'Launch new website',
        task: 'Disable auto description meta tag create via Theme Settings',
        completed: false,
    },
    {
        id: 29,
        category: 'Launch new website',
        task: 'Contact forms should use WPForms forms (case-to-case)',
        completed: false,
    },
    {
        id: 30,
        category: 'Launch new website',
        task: 'Every contact form should have Referrer URL',
        completed: false,
    },
    {
        id: 31,
        category: 'Launch new website',
        task: 'Form fields should be set to required',
        completed: false,
    },
    {
        id: 32,
        category: 'Launch new website',
        task: 'Form Email Subject Line should follow correct format',
        completed: false,
    },
    {
        id: 33,
        category: 'Launch new website',
        task: 'Form Reply-to setting should be set to Email Field',
        completed: false,
    },
    {
        id: 34,
        category: 'Launch new website',
        task: 'From Name should be set to Company Name',
        completed: false,
    },
    {
        id: 35,
        category: 'Launch new website',
        task: 'From Email-from should be set to no-reply@domain.com',
        completed: false,
    },
    {
        id: 36,
        category: 'Launch new website',
        task: 'Contact forms should redirect to Thank You page after sending',
        completed: false,
    },
    {
        id: 37,
        category: 'Launch new website',
        task: 'Make sure the forms are working',
        completed: false,
    },
    {
        id: 38,
        category: 'Launch new website',
        task: 'Verify email recipient for contact form and CC tcjleads@gmail.com',
        completed: false,
    },
    {
        id: 39,
        category: 'Launch new website',
        task: 'Make sure page title / main page heading is using H1 tag',
        completed: false,
    },
    {
        id: 40,
        category: 'Launch new website',
        task: 'Coordinate with the Google Ads team for exact phone number',
        completed: false,
    },
    {
        id: 41,
        category: 'Launch new website',
        task: 'Make sure all numbers are clickable for direct call',
        completed: false,
    },
    {
        id: 42,
        category: 'Launch new website',
        task: 'Make sure site is optimized on mobile',
        completed: false,
    },
    {
        id: 43,
        category: 'Launch new website',
        task: 'Make sure to have privacy policy and terms pages',
        completed: false,
    },
    {
        id: 44,
        category: 'Launch new website',
        task: 'Designate the Page as Your Privacy Policy in WordPress Settings',
        completed: false,
    },
    {
        id: 45,
        category: 'Launch new website',
        task: 'Make sure images have alt tags',
        completed: false,
    },
    {
        id: 46,
        category: 'Launch new website',
        task: 'Add an OpenGraph thumbnail via Rank Math',
        completed: false,
    },
    {
        id: 47,
        category: 'Launch new website',
        task: 'Add blog page if there’s none existing',
        completed: false,
    },
    {
        id: 48,
        category: 'Launch new website',
        task: 'Only show blog page if there are at least 2 blog posts',
        completed: false,
    },
    {
        id: 49,
        category: 'Launch new website',
        task: 'Create single post template for blog posts',
        completed: false,
    },
    {
        id: 50,
        category: 'Launch new website',
        task: 'Blog URLs should be /blog/[blog-name]',
        completed: false,
    },
    {
        id: 51,
        category: 'Launch new website',
        task: 'Blog author name should be Client’s name',
        completed: false,
    },
    {
        id: 52,
        category: 'Launch new website',
        task: 'Create account for blog writers (Editor role / writer@topclickjoe.com / writer / MOBdg!@os3stP&8TNfZpk!9k)',
        completed: false,
    },
    {
        id: 53,
        category: 'Launch new website',
        task: 'Create account for pillar writers (Editor role / pillar@topclickjoe.com / pillar / FCwIaDH4$GpDW0gy(i75Qa!Q)',
        completed: false,
    },
    {
        id: 54,
        category: 'Launch new website',
        task: 'Create account for SEO users (Editor role / seo@topclickjoe.com / tcjseo / T6Kxq132(CwUnENCow#v0QEn)',
        completed: false,
    },
    {
        id: 55,
        category: 'Launch new website',
        task: 'Call Now buttons should be numbers for tracking',
        completed: false,
    },
    {
        id: 56,
        category: 'Launch new website',
        task: 'Numbers should be very visible',
        completed: false,
    },
    {
        id: 57,
        category: 'Launch new website',
        task: 'Perform #google-wcc-debug to double check on the numbers',
        completed: false,
    },
    {
        id: 58,
        category: 'Launch new website',
        task: 'If site is cloned, use Better Search & Replace plugin',
        completed: false,
    },
    {
        id: 59,
        category: 'Launch new website',
        task: 'Install Hotjar tracking',
        completed: false,
    },
    {
        id: 60,
        category: 'Launch new website',
        task: 'Coordinate with PPC team on what landing page to create',
        completed: false,
    },
    {
        id: 61,
        category: 'Launch new website',
        task: 'URL of landing pages should be /ppc/[service-url]',
        completed: false,
    },
    {
        id: 62,
        category: 'Launch new website',
        task: 'Make sure PPC pages has noindex/nofollow tag',
        completed: false,
    },
    {
        id: 63,
        category: 'Launch new website',
        task: 'Link review badge to testimonial section',
        completed: false,
    },
    {
        id: 64,
        category: 'Launch new website',
        task: 'Remove select service on PPC forms',
        completed: false,
    },
    {
        id: 65,
        category: 'Launch new website',
        task: 'PPC landing pages should have no outgoing links',
        completed: false,
    },
    {
        id: 66,
        category: 'Launch new website',
        task: 'Add Honeypot field for PPC landing pages',
        completed: false,
    },
    {
        id: 67,
        category: 'Launch new website',
        task: 'Install Honeypot code via Elementor',
        completed: false,
    },
    {
        id: 68,
        category: 'Launch new website',
        task: 'Service page form titles should match service',
        completed: false,
    },
    {
        id: 69,
        category: 'Launch new website',
        task: 'SEO/front pages should have appealing headlines',
        completed: false,
    },
    {
        id: 70,
        category: 'Launch new website',
        task: 'Send PPC landing page URLs to PPC team',
        completed: false,
    },
    {
        id: 71,
        category: 'Launch new website',
        task: 'Add sitemap page and footer menu item',
        completed: false,
    },
    {
        id: 72,
        category: 'Launch new website',
        task: 'Service pages URL structure should be /services/[service-name]',
        completed: false,
    },
    {
        id: 73,
        category: 'Launch new website',
        task: 'Add Resources page for pillar pages',
        completed: false,
    },
    {
        id: 74,
        category: 'Launch new website',
        task: 'Enable Excerpt for pages',
        completed: false,
    },
    {
        id: 75,
        category: 'Launch new website',
        task: 'Pillar page URL structure should be /resources/[pillar-page-title]',
        completed: false,
    },
    {
        id: 76,
        category: 'Launch new website',
        task: 'Block all countries except PH and client country',
        completed: false,
    },
    {
        id: 77,
        category: 'Launch new website',
        task: 'Add 404 page template',
        completed: false,
    },
    {
        id: 78,
        category: 'Launch new website',
        task: 'Uncheck Discourage search engines from indexing this site',
        completed: false,
    },
];